### ISSUE TITLE
'Like' a tweet

### ISSUE THREAD

**Issue by mikes1980** [jflessau/winbot-twitter-bot#5]
Hi,

Are you looking at adding a 'like' function to your code?  A lot of competitions want you to like & retweet.

Keep up the good work!

**Comment by jflessau** [comment]
Hi Mike,

Liking something is another interaction through the API and will cost some time (because of twitters interaction limits).
That's why I'm planning to add a function to like a tweet, only if the word 'like' or 'liking'  (e.g. "dont forget liking this tweet") can be found somewhere in a tweet. Should be done within this week :)

**Comment by mikes1980** [comment]
Sounds good!!
